# This workflow runs checks againts pull request or current codebase at master branc
name: checks

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: lint
      run: make lint
  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      
    - name: test
      run: make test-coverage
    
    - name: install goveralls
      run: GO111MODULE=off go get -u github.com/mattn/goveralls
      
    - name: submit coverage
      run: $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=coverage.out
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
